# spring:
#   jpa:
#     database: POSTGRESQL
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#       use-new-id-generator-mappings: true
#     properties:
#       hibernate.jdbc.batch_size: 50
#       hibernate.cache.use_query_cache: false
#       hibernate.cache.use_second_level_cache: false
#       hibernate.cache.use_structured_entries: false
#       hibernate.cache.use_minimal_puts: false
#       hibernate.temp.use_jdbc_metadata_defaults: false
#   datasource:
#     platform: postgres
#     url: jdbc:postgresql://localhost:5432/jpa
#     username: postgres
#     password: postgres
#     driverClassName: org.postgresql.Driver
